Fix open source build by linking against libthriftmetadata.so (#176)
Summary:
Pull Request resolved: https://github.com/facebookincubator/LogDevice/pull/176

Fix OSS build error:

```
/usr/bin/ld: ../../lib/libadmin-cpp2.a(admin_metadata.cpp.o): undefined reference to symbol '_ZNKR6apache6thrift8metadata20ThriftServiceContext16get_service_infoEv'
//root/project/_build/fbthrift-prefix/src/fbthrift-build/lib/libthriftmetadata.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

Reviewed By: AhmedSoliman

Differential Revision: D20257545

fbshipit-source-id: 75db1cc4c4b9ed0f56f6565af78b5509a8a8b951